config/routes.rb
FeedMyFreebox::Application.routes.draw do
  resources :teams

  get "episode/update"

  get "episode/pick_torrent"

  get "episode/send"

  get "freeboxes/attach"
  get "freeboxes/get"
  get "freeboxes/confirm"

  get "login/return"
  get "login/index"
  get "login/", to: 'login#index'

  resources :tv_shows

end

app/models/tv_show.rb
require_relative 'episode'

class TvShow < ActiveRecord::Base
  has_many :followers
  has_many :users, through: :followers
  has_many :episodes
  attr_accessible :betaseries_id, :title

  def fetch_subtitles_available(user_token, teams)
    @episodes.each{|e| e.fetch_subtitles_available(user_token, teams)}
  end

end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  # GET /tv_shows
  # GET /tv_shows.json
  def index
    @tv_shows = TvShow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tv_shows }
    end
  end

  # GET /tv_shows/1
  # GET /tv_shows/1.json
  def show
    @tv_show = TvShow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tv_show }
    end
  end

  # GET /tv_shows/new
  # GET /tv_shows/new.json
  def new
    @tv_show = TvShow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tv_show }
    end
  end



  # GET /tv_shows/1/edit
  def edit
    @tv_show = TvShow.find(params[:id])
  end

  # POST /tv_shows
  # POST /tv_shows.json
  def create
    @tv_show = TvShow.new(params[:tv_show])

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully created.' }
        format.json { render json: @tv_show, status: :created, location: @tv_show }
      else
        format.html { render action: "new" }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tv_shows/1
  # PUT /tv_shows/1.json
  def update
    @tv_show = TvShow.find(params[:id])

    respond_to do |format|
      if @tv_show.update_attributes(params[:tv_show])
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  def load_torrent
    @tv_show = TvShow.find(params[:id])

  end

  # DELETE /tv_shows/1
  # DELETE /tv_shows/1.json
  def destroy
    @tv_show = TvShow.find(params[:id])
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/tv_shows/_form.html.erb
<%= form_for(@tv_show) do |f| %>
  <% if @tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
      <% @tv_show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Editing tv_show</h1>

<%= render 'form' %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<h1>Listing tv_shows</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tv_shows.each do |tv_show| %>
  <tr>
    <td><%= tv_show.name %></td>
    <td><%= link_to 'Show', tv_show %></td>
    <td><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
    <td><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tv show', new_tv_show_path %>

app/views/tv_shows/new.html.erb
<h1>New tv_show</h1>

<%= render 'form' %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tv_show.name %>
</p>


<%= link_to 'Edit', edit_tv_show_path(@tv_show) %> |
<%= link_to 'Back', tv_shows_path %>